version: '3.8'

services:
  openhands:
    image: docker.all-hands.dev/all-hands-ai/openhands:0.40
    container_name: openhands-app
    environment:
      - SANDBOX_RUNTIME_CONTAINER_IMAGE=docker.all-hands.dev/all-hands-ai/runtime:0.40-nikolaik
      - LOG_ALL_EVENTS=true
    ports:
      - "13000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - openhands-state:/.openhands-state
    extra_hosts:
      - "host.docker.internal:host-gateway"
    stdin_open: true
    tty: true

  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n-app
    ports:
      - "13004:5678"
    environment:
      - GENERIC_TIMEZONE=Asia/Tokyo
      - TZ=Asia/Tokyo
      - N8N_SECURE_COOKIE=false
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped

volumes:
  openhands-state:
  n8n_data:
